name: javascript
version: 0.1.0.0
github: "githubuser/javascript"
license: BSD3
author: "Łukasz Karczewski"
maintainer: "example@example.com"
copyright: "2021 Łukasz Karczewski"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/javascript#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  javascript-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - javascript

tests:
  javascript-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - javascript
